### ISSUE TITLE
Change sets from mongodb?

### ISSUE THREAD

**Issue by gedw99** [amirhnajafiz/telegraph#1]
Does it send changes from mongo db out ?

It would mean that other systems can change the db and then nats and anything using nats gets the data real time .

can help with this if needed

**Comment by amirhnajafiz** [comment]
Dear @gedw99 I see what you mean and this is an interesting idea, but we already have ```debezium``` which does the same thing for us.

If you are interested I suggest that you take a look at this example.
[github.com/amirhossein-teaching/debezium](https://github.com/amirhossein-teaching/debezium)

But I agree with you, we can build a service like ```debezium``` which listens over a ```mongodb``` cluster
and publishes databases actions as an event on ```nats```.
If you are also interested in doing that, I suggest that we create a new repository and start building it.

**Comment by gedw99** [comment]
Checkout conduit … 

https://github.com/conduitio-labs

it also works
